# Generated by Django 3.2.6 on 2021-08-05 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='barbearia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.barbearia'),
        ),
    ]
