# Generated by Django 3.2.6 on 2021-08-05 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_servico_barbearia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem_servico',
            name='barbearia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.barbearia'),
        ),
        migrations.AlterField(
            model_name='ordem_servico',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.cliente'),
        ),
        migrations.AlterField(
            model_name='ordem_servico',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.servico'),
        ),
    ]
