# Generated by Django 3.2.6 on 2021-08-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210805_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbearia',
            name='date_closed',
            field=models.DateField(null=True),
        ),
    ]
