# Generated by Django 3.2.6 on 2021-08-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210809_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbearia',
            name='endereco_lat',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='barbearia',
            name='endereco_lng',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco_lat',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco_lng',
            field=models.DecimalField(decimal_places=8, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
