# Generated by Django 3.2.6 on 2021-08-24 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210818_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordem_servico',
            name='comentario',
        ),
    ]
